# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmM2ZWU3MjRjOTEyODA2MjgzYjNkYTI3MjBmOTY0Y2MxNzZlMzhmNmVkZGFjMzU5NzU5MjUwZTg3Y2JkOGRjYWQyMzU3MGU4MTUzYzhhYjc3ZWM2ZjJjOWI0YzUzNWY3NTE3OWY3NDFiOTFkODE3NWE4NjJlYzJmNGY1NDJkZGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
